copyright: Copyright &copy; 2024 <a href="https://zkfold.io" target="_blank" rel="noopener">zkFold SA</a>
site_name: "zkFold Products User Documentation"
site_url: https://docs.zkfold.io
repo_url: https://github.com/zkFold
repo_name: zkFold's GitHub
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc
    - toc.follow
    # - toc.integrate
    - navigation.top
    # - header.autohide
    # - announce.dismiss
    - navigation.footer
    - search
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.annotate
    - content.code.copy
    - content.code.select
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent:  orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent:  orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  language: en

extra:
  # generator: false
  homepage: https://docs.zkfold.io/products
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/zkFold
      name: zkFold's X Account
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/zkFold
      name: zkFold's LinkedIn Page
    - icon: fontawesome/brands/github
      link: https://github.com/zkFold
      name: zkFold's GitHub
  alternate:
    - name: English
      link: /
      lang: en

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - social
  - search

nav:
  - zkFold:
    - Products: 'products.md'
    - About: 'about.md'
  - Symbolic:
    - Introduction: symbolic/introduction.md
    - "Coding in Symbolic":
      - "Getting Started": symbolic/coding/getting-started.md
      - "Basic Types": symbolic/coding/basic-types.md
      - "Custom Types": symbolic/coding/custom-types.md
      - "DSL": symbolic/coding/DSL.md
    - "Smart Contracts":
      - "Basics": symbolic/smart-contracts/basics.md
      - "Cardano":
        - "Cardano": symbolic/smart-contracts/cardano/index.md
        - "Plonk Verifier": symbolic/smart-contracts/cardano/plonk-verifier.md
        - "Symbolic Verifier": symbolic/smart-contracts/cardano/symbolic-verifier.md
        - "Transactions": symbolic/smart-contracts/cardano/transactions.md
      - "Symbolic Ledger": symbolic/smart-contracts/symbolic-ledger.md
    - "Tools":
      - "Symbolic CLI": symbolic/tools/cli.md
      - "Circom Converter": symbolic/tools/circom-converter.md
      - "UPLC Converter": symbolic/tools/uplc-converter.md
  - "L2 Solutions":
    - "L2 Solutions": 'L2/index.md'
    # - "Symbolic Ledger": 'L2/symbolic-ledger.md'
    - Rollup: 'L2/rollup.md'
    - Sidechain: 'L2/sidechain.md'
  - "Other zkApps":
    - "Other zkApps": other-zkapps/index.md
    - "Mithril Bridge": other-zkapps/mithril-bridge.md
    - "Wallet Backend": other-zkapps/wallet-backend.md
    - "ZK-KYC Protocol": other-zkapps/zk-kyc.md
    - "zkPass Verifier": other-zkapps/zkpass.md
    - "P2P On-Ramp": other-zkapps/p2p-on-ramp.md
