name: Update Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.10'
      - uses: actions/cache@v4.0.2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-redirects
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force